#!/bin/bash
set -e
export PATH=/bin

chmod 444 /challenge/*.md /challenge/*.gz

tar xf /challenge/ips.tar.gz -C /challenge

/opt/linux/linux-5.4/scripts/extract-vmlinux \
	/challenge/bzImage > /challenge/vmlinux

